### ISSUE TITLE
Plugin doesn't work with SonarQube 7.3

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [checkstyle/sonar-checkstyle#157]
Sonar version: 7.3
Checkstyle sonar plugin verson: 4.11

Steps to reproduce or description of problem:

Plugin doesn't work with SonarQube 7.3:
`java.lang.IllegalStateException: Fail to load plugin Checkstyle [checkstyle]
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/batch/Sensor
`
Caused by https://jira.sonarsource.com/browse/SONAR-10138.

See also https://github.com/checkstyle/sonar-checkstyle/issues/134

On sonar 7.4
```
2018.12.25 17:05:39 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin Checkstyle [checkstyle]
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
        at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:586)
        at org.sonar.server.platform.Platform.start(Platform.java:211)
        at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
        at org.sonar.server.platform.Platform.access$500(Platform.java:46)
        at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
        at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/batch/Sensor
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        at org.sonar.plugins.checkstyle.CheckstylePlugin.getExtensions(CheckstylePlugin.java:84)
        at org.sonar.api.SonarPlugin.define(SonarPlugin.java:51)
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:72)
        ... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.batch.Sensor
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        ... 25 common frames omitted

```

sonarqube downloads: https://www.sonarqube.org/downloads/ (6.7 is LST, 7.5 latest)
https://hub.docker.com/_/sonarqube/ (6.7-community , 7.5-comminity)

**Comment by romani** [comment]
sad .... looks like API changes now affecting us.

if smb have a time .... please fill free to provide fix .

**Comment by muhlba91** [comment]
any information on this issue? can we expect a merge and new version soon? :)

**Comment by rnveach** [comment]
@muhlba91 
Some work was going on at https://github.com/checkstyle/sonar-checkstyle/pull/158 but it seems contributor stopped.
Checkstyle team doesn't know sonar very well so we need help fixing and validating.

**Comment by muhlba91** [comment]
@rnveach I quickly read through the discussion in the linked PR. Can I help in getting it merged so that the integration with SonarQube 7.3 works again?

**Comment by rnveach** [comment]
Other PR has gone stale since Oct. So there shouldn't be any conflict.

**Comment by muhlba91** [comment]
Great, I already updated dependencies and got a working version locally.
However, due to quite a few API changes, I‘m in the process of fixing some tests.

**Comment by muhlba91** [comment]
@rnveach please find fix in PR #165 but I need a bit of support with 2 (now ignored) test cases and your CI builds which are failing due to reasons I do not know, unfortunately. I commented in PR.

**Comment by charlesfendt** [comment]
> 2018.11.15 14:25:05 ERROR web[][o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.web.PlatformServletContextListener
> org.sonar.api.utils.MessageException: Plugin Checkstyle [checkstyle] requires at least SonarQube 7.2
> 2018.11.15 14:25:05 ERROR web[][o.a.c.c.StandardContext] One or more listeners failed to start. Full details will be found in the appropriate container log file
> 

It seems the build try to start an sonarqube instance with the with compiled version of the plugin... and it failed !
If your patch needs sonarqube 7.2 or more, someone has to change the build script :-/

**Comment by muhlba91** [comment]
@charlesfendt please see #166

**Comment by ediri** [comment]
hi,

looking forward for the fix of the plugin to use with Sonarqube 7.3! Thumbs up for your good work!

**Comment by jaune162** [comment]
It's doesn't work with Sonarqube 7.5 too.

**Comment by bhalothia** [comment]
It doesn't work for 7.4-community-alpine too.

**Comment by romani** [comment]
fix is merged
will be released at the end of January

**Comment by YevheniiKokhanevych** [comment]
@romani, when will be available fix version?

**Comment by muhlba91** [comment]
i'd guess mid of february (see: https://community.sonarsource.com/t/rff-checkstyle-plugin-4-17/6192)

**Comment by ediri** [comment]
@YevheniiKokhanevych just download it from the github release page and install manually on the server/container. Its is quicker then waiting. We did and it works like a charme!
